<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
	<xsl:output omit-xml-declaration="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>

	<!-- Empire_N -->
	<xsl:template match="Settlement[@id='town_EN1']"/>
	<xsl:template match="Settlement[@id='village_EN1_1']"/>
	<xsl:template match="Settlement[@id='village_EN1_2']"/>
	<xsl:template match="Settlement[@id='village_EN1_3']"/>
	<xsl:template match="Settlement[@id='town_EN2']"/>
	<xsl:template match="Settlement[@id='village_EN2_1']"/>
	<xsl:template match="Settlement[@id='village_EN2_2']"/>
	<xsl:template match="Settlement[@id='town_EN3']"/>
	<xsl:template match="Settlement[@id='village_EN3_1']"/>
	<xsl:template match="Settlement[@id='village_EN3_3']"/>
	<xsl:template match="Settlement[@id='town_EN4']"/>
	<xsl:template match="Settlement[@id='village_EN4_2']"/>
	<xsl:template match="Settlement[@id='village_EN4_4']"/>
	<xsl:template match="Settlement[@id='town_EN5']"/>
	<xsl:template match="Settlement[@id='village_EN5_1']"/>
	<xsl:template match="Settlement[@id='village_EN5_2']"/>
	<xsl:template match="Settlement[@id='village_EN5_4']"/>
	<xsl:template match="Settlement[@id='town_EN6']"/>
	<xsl:template match="Settlement[@id='village_EN6_1']"/>
	<xsl:template match="Settlement[@id='village_EN6_2']"/>
	<!-- Castles -->
	<xsl:template match="Settlement[@id='castle_EN1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN1_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN1_2']"/>
	<xsl:template match="Settlement[@id='castle_EN2']"/>
	<xsl:template match="Settlement[@id='castle_village_EN2_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN2_2']"/>
	<xsl:template match="Settlement[@id='castle_EN3']"/>
	<xsl:template match="Settlement[@id='castle_village_EN3_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN3_2']"/>
	<xsl:template match="Settlement[@id='castle_EN4']"/>
	<xsl:template match="Settlement[@id='castle_village_EN4_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN4_2']"/>
	<xsl:template match="Settlement[@id='castle_EN5']"/>
	<xsl:template match="Settlement[@id='castle_village_EN5_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN5_2']"/>
	<xsl:template match="Settlement[@id='castle_EN6']"/>
	<xsl:template match="Settlement[@id='castle_village_EN6_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN6_2']"/>
	<xsl:template match="Settlement[@id='castle_EN7']"/>
	<xsl:template match="Settlement[@id='castle_village_EN7_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN7_2']"/>
	<xsl:template match="Settlement[@id='castle_EN8']"/>
	<xsl:template match="Settlement[@id='castle_village_EN8_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN8_2']"/>
	<xsl:template match="Settlement[@id='castle_EN9']"/>
	<xsl:template match="Settlement[@id='castle_village_EN9_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EN9_2']"/>
	
	<!-- Empire_W -->
	<xsl:template match="Settlement[@id='town_EW1']"/>
	<xsl:template match="Settlement[@id='village_EW1_1']"/>
	<xsl:template match="Settlement[@id='village_EW1_2']"/>
	<xsl:template match="Settlement[@id='town_EW2']"/>
	<xsl:template match="Settlement[@id='village_EW2_2']"/>
	<xsl:template match="Settlement[@id='village_EW2_3']"/>
	<xsl:template match="Settlement[@id='village_EW2_4']"/>
	<xsl:template match="Settlement[@id='town_EW3']"/>
	<xsl:template match="Settlement[@id='village_EW3_2']"/>
	<xsl:template match="Settlement[@id='village_EW3_3']"/>
	<xsl:template match="Settlement[@id='town_EW4']"/>
	<xsl:template match="Settlement[@id='village_EW4_1']"/>
	<xsl:template match="Settlement[@id='village_EW4_3']"/>
	<xsl:template match="Settlement[@id='village_EW4_4']"/>
	<xsl:template match="Settlement[@id='town_EW5']"/>
	<xsl:template match="Settlement[@id='village_EW5_1']"/>
	<xsl:template match="Settlement[@id='village_EW5_2']"/>
	<xsl:template match="Settlement[@id='town_EW6']"/>
	<xsl:template match="Settlement[@id='village_EW6_1']"/>
	<xsl:template match="Settlement[@id='village_EW6_3']"/>
	<xsl:template match="Settlement[@id='village_EW6_4']"/>
	<!-- Castles -->
	<xsl:template match="Settlement[@id='castle_EW1']"/>
	<xsl:template match="Settlement[@id='castle_village_EW1_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EW1_2']"/>
	<xsl:template match="Settlement[@id='castle_EW2']"/>
	<xsl:template match="Settlement[@id='castle_village_EW2_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EW2_2']"/>
	<xsl:template match="Settlement[@id='castle_EW3']"/>
	<xsl:template match="Settlement[@id='castle_village_EW3_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EW3_2']"/>
	<xsl:template match="Settlement[@id='castle_EW4']"/>
	<xsl:template match="Settlement[@id='castle_village_EW4_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EW4_2']"/>
	<xsl:template match="Settlement[@id='castle_EW5']"/>
	<xsl:template match="Settlement[@id='castle_village_EW5_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EW5_2']"/>
	<xsl:template match="Settlement[@id='castle_EW6']"/>
	<xsl:template match="Settlement[@id='castle_village_EW6_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EW6_2']"/>
	<xsl:template match="Settlement[@id='castle_EW7']"/>
	<xsl:template match="Settlement[@id='castle_village_EW7_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EW7_2']"/>
	<xsl:template match="Settlement[@id='castle_EW8']"/>
	<xsl:template match="Settlement[@id='castle_village_EW8_1']"/>
	<xsl:template match="Settlement[@id='castle_village_EW8_2']"/>
	
	<!-- Empire_S -->
	<xsl:template match="Settlement[@id='town_ES1']"/>
	<xsl:template match="Settlement[@id='village_ES1_2']"/>
	<xsl:template match="Settlement[@id='village_ES1_3']"/>
	<xsl:template match="Settlement[@id='village_ES1_4']"/>
	<xsl:template match="Settlement[@id='town_ES2']"/>
	<xsl:template match="Settlement[@id='village_ES2_2']"/>
	<xsl:template match="Settlement[@id='village_ES2_3']"/>
	<xsl:template match="Settlement[@id='village_ES2_4']"/>
	<xsl:template match="Settlement[@id='town_ES3']"/>
	<xsl:template match="Settlement[@id='village_ES3_1']"/>
	<xsl:template match="Settlement[@id='village_ES3_2']"/>
	<xsl:template match="Settlement[@id='village_ES3_3']"/>
	<xsl:template match="Settlement[@id='town_ES4']"/>
	<xsl:template match="Settlement[@id='village_ES4_1']"/>
	<xsl:template match="Settlement[@id='village_ES4_3']"/>
	<xsl:template match="Settlement[@id='town_ES5']"/>
	<xsl:template match="Settlement[@id='village_ES5_1']"/>
	<xsl:template match="Settlement[@id='village_ES5_2']"/>
	<xsl:template match="Settlement[@id='village_ES5_3']"/>
	<xsl:template match="Settlement[@id='town_ES6']"/>
	<xsl:template match="Settlement[@id='village_ES6_1']"/>
	<xsl:template match="Settlement[@id='village_ES6_2']"/>
	<xsl:template match="Settlement[@id='town_ES7']"/>
	<xsl:template match="Settlement[@id='village_ES7_1']"/>
	<xsl:template match="Settlement[@id='village_ES7_2']"/>
	<!-- Castles -->
	<xsl:template match="Settlement[@id='castle_ES1']"/>
	<xsl:template match="Settlement[@id='castle_village_ES1_1']"/>
	<xsl:template match="Settlement[@id='castle_village_ES1_2']"/>
	<xsl:template match="Settlement[@id='castle_ES2']"/>
	<xsl:template match="Settlement[@id='castle_village_ES2_1']"/>
	<xsl:template match="Settlement[@id='castle_village_ES2_2']"/>
	<xsl:template match="Settlement[@id='castle_ES3']"/>
	<xsl:template match="Settlement[@id='castle_village_ES3_1']"/>
	<xsl:template match="Settlement[@id='castle_village_ES3_2']"/>
	<xsl:template match="Settlement[@id='castle_ES4']"/>
	<xsl:template match="Settlement[@id='castle_village_ES4_1']"/>
	<xsl:template match="Settlement[@id='castle_village_ES4_2']"/>
	<xsl:template match="Settlement[@id='castle_ES5']"/>
	<xsl:template match="Settlement[@id='castle_village_ES5_1']"/>
	<xsl:template match="Settlement[@id='castle_village_ES5_2']"/>
	<xsl:template match="Settlement[@id='castle_ES6']"/>
	<xsl:template match="Settlement[@id='castle_village_ES6_1']"/>
	<xsl:template match="Settlement[@id='castle_village_ES6_2']"/>
	<xsl:template match="Settlement[@id='castle_ES7']"/>
	<xsl:template match="Settlement[@id='castle_village_ES7_1']"/>
	<xsl:template match="Settlement[@id='castle_village_ES7_2']"/>
	<xsl:template match="Settlement[@id='castle_ES8']"/>
	<xsl:template match="Settlement[@id='castle_village_ES8_1']"/>
	<xsl:template match="Settlement[@id='castle_village_ES8_2']"/>
	
	<!-- Sturgia -->
	<xsl:template match="Settlement[@id='town_S1']"/>
	<xsl:template match="Settlement[@id='village_S1_1']"/>
	<xsl:template match="Settlement[@id='village_S1_3']"/>
	<xsl:template match="Settlement[@id='town_S2']"/>
	<xsl:template match="Settlement[@id='village_S2_1']"/>
	<xsl:template match="Settlement[@id='village_S2_2']"/>
	<xsl:template match="Settlement[@id='town_S3']"/>
	<xsl:template match="Settlement[@id='village_S3_1']"/>
	<xsl:template match="Settlement[@id='village_S3_2']"/>
	<xsl:template match="Settlement[@id='town_S4']"/>
	<xsl:template match="Settlement[@id='village_S4_1']"/>
	<xsl:template match="Settlement[@id='village_S4_3']"/>
	<xsl:template match="Settlement[@id='village_S4_4']"/>
	<xsl:template match="Settlement[@id='town_S5']"/>
	<xsl:template match="Settlement[@id='village_S5_1']"/>
	<xsl:template match="Settlement[@id='village_S5_2']"/>
	<xsl:template match="Settlement[@id='town_S6']"/>
	<xsl:template match="Settlement[@id='village_S6_1']"/>
	<xsl:template match="Settlement[@id='village_S6_2']"/>
	<xsl:template match="Settlement[@id='village_S6_3']"/>
	<xsl:template match="Settlement[@id='town_S7']"/>
	<xsl:template match="Settlement[@id='village_S7_1']"/>
	<xsl:template match="Settlement[@id='village_S7_2']"/>
	<!-- Castles -->
	<xsl:template match="Settlement[@id='castle_S1']"/>
	<xsl:template match="Settlement[@id='castle_village_S1_1']"/>
	<xsl:template match="Settlement[@id='castle_village_S1_2']"/>
	<xsl:template match="Settlement[@id='castle_S2']"/>
	<xsl:template match="Settlement[@id='castle_village_S2_1']"/>
	<xsl:template match="Settlement[@id='castle_village_S2_2']"/>
	<xsl:template match="Settlement[@id='castle_S3']"/>
	<xsl:template match="Settlement[@id='castle_village_S3_1']"/>
	<xsl:template match="Settlement[@id='castle_village_S3_2']"/>
	<xsl:template match="Settlement[@id='castle_S4']"/>
	<xsl:template match="Settlement[@id='castle_village_S4_1']"/>
	<xsl:template match="Settlement[@id='castle_village_S4_2']"/>
	<xsl:template match="Settlement[@id='castle_S5']"/>
	<xsl:template match="Settlement[@id='castle_village_S5_1']"/>
	<xsl:template match="Settlement[@id='castle_village_S5_2']"/>
	<xsl:template match="Settlement[@id='castle_S6']"/>
	<xsl:template match="Settlement[@id='castle_village_S6_1']"/>
	<xsl:template match="Settlement[@id='castle_village_S6_2']"/>
	<xsl:template match="Settlement[@id='castle_S7']"/>
	<xsl:template match="Settlement[@id='castle_village_S7_1']"/>
	<xsl:template match="Settlement[@id='castle_village_S7_2']"/>
	<xsl:template match="Settlement[@id='castle_S8']"/>
	<xsl:template match="Settlement[@id='castle_village_S8_1']"/>
	<xsl:template match="Settlement[@id='castle_village_S8_2']"/>
	
	<!-- Aserai -->
	<xsl:template match="Settlement[@id='town_A1']"/>
	<xsl:template match="Settlement[@id='village_A1_1']"/>
	<xsl:template match="Settlement[@id='village_A1_2']"/>
	<xsl:template match="Settlement[@id='village_A1_4']"/>
	<xsl:template match="Settlement[@id='town_A2']"/>
	<xsl:template match="Settlement[@id='village_A2_2']"/>
	<xsl:template match="Settlement[@id='village_A2_3']"/>
	<xsl:template match="Settlement[@id='town_A3']"/>
	<xsl:template match="Settlement[@id='village_A3_1']"/>
	<xsl:template match="Settlement[@id='village_A3_3']"/>
	<xsl:template match="Settlement[@id='town_A4']"/>
	<xsl:template match="Settlement[@id='village_A4_1']"/>
	<xsl:template match="Settlement[@id='village_A4_2']"/>
	<xsl:template match="Settlement[@id='village_A4_4']"/>
	<xsl:template match="Settlement[@id='town_A5']"/>
	<xsl:template match="Settlement[@id='village_A5_1']"/>
	<xsl:template match="Settlement[@id='village_A5_2']"/>
	<xsl:template match="Settlement[@id='village_A5_3']"/>
	<xsl:template match="Settlement[@id='town_A6']"/>
	<xsl:template match="Settlement[@id='village_A6_1']"/>
	<xsl:template match="Settlement[@id='village_A6_2']"/>
	<xsl:template match="Settlement[@id='village_A6_3']"/>
	<xsl:template match="Settlement[@id='village_A6_4']"/>
	<xsl:template match="Settlement[@id='town_A7']"/>
	<xsl:template match="Settlement[@id='village_A7_2']"/>
	<xsl:template match="Settlement[@id='village_A7_3']"/>
	<xsl:template match="Settlement[@id='village_A7_4']"/>
	<xsl:template match="Settlement[@id='town_A8']"/>
	<xsl:template match="Settlement[@id='village_A8_1']"/>
	<xsl:template match="Settlement[@id='village_A8_2']"/>
	<!-- Castles -->
	<xsl:template match="Settlement[@id='castle_A1']"/>
	<xsl:template match="Settlement[@id='castle_village_A1_1']"/>
	<xsl:template match="Settlement[@id='castle_village_A1_2']"/>
	<xsl:template match="Settlement[@id='castle_A2']"/>
	<xsl:template match="Settlement[@id='castle_village_A2_1']"/>
	<xsl:template match="Settlement[@id='castle_village_A2_2']"/>
	<xsl:template match="Settlement[@id='castle_A3']"/>
	<xsl:template match="Settlement[@id='castle_village_A3_1']"/>
	<xsl:template match="Settlement[@id='castle_village_A3_2']"/>
	<xsl:template match="Settlement[@id='castle_A4']"/>
	<xsl:template match="Settlement[@id='castle_village_A4_1']"/>
	<xsl:template match="Settlement[@id='castle_village_A4_2']"/>
	<xsl:template match="Settlement[@id='castle_A5']"/>
	<xsl:template match="Settlement[@id='castle_village_A5_1']"/>
	<xsl:template match="Settlement[@id='castle_village_A5_2']"/>
	<xsl:template match="Settlement[@id='castle_A6']"/>
	<xsl:template match="Settlement[@id='castle_village_A6_1']"/>
	<xsl:template match="Settlement[@id='castle_village_A6_2']"/>
	<xsl:template match="Settlement[@id='castle_A7']"/>
	<xsl:template match="Settlement[@id='castle_village_A7_1']"/>
	<xsl:template match="Settlement[@id='castle_village_A7_2']"/>
	<xsl:template match="Settlement[@id='castle_A8']"/>
	<xsl:template match="Settlement[@id='castle_village_A8_1']"/>
	<xsl:template match="Settlement[@id='castle_village_A8_2']"/>
	<xsl:template match="Settlement[@id='castle_A9']"/>
	<xsl:template match="Settlement[@id='castle_village_A9_1']"/>
	<xsl:template match="Settlement[@id='castle_village_A9_2']"/>
	
	<!-- Vlandia -->
	<xsl:template match="Settlement[@id='town_V1']"/>
	<xsl:template match="Settlement[@id='village_V1_1']"/>
	<xsl:template match="Settlement[@id='village_V1_2']"/>
	<xsl:template match="Settlement[@id='town_V2']"/>
	<xsl:template match="Settlement[@id='village_V2_1']"/>
	<xsl:template match="Settlement[@id='village_V2_2']"/>
	<xsl:template match="Settlement[@id='village_V2_3']"/>
	<xsl:template match="Settlement[@id='town_V3']"/>
	<xsl:template match="Settlement[@id='village_V3_2']"/>
	<xsl:template match="Settlement[@id='village_V3_3']"/>
	<xsl:template match="Settlement[@id='village_V3_4']"/>
<!-- 	<xsl:template match="Settlement[@id='town_V4']"/>
	<xsl:template match="Settlement[@id='village_V4_1']"/> -->
	<xsl:template match="Settlement[@id='town_V5']"/>
	<xsl:template match="Settlement[@id='village_V5_1']"/>
	<xsl:template match="Settlement[@id='village_V5_2']"/>
	<xsl:template match="Settlement[@id='village_V5_3']"/>
	<xsl:template match="Settlement[@id='town_V6']"/>
	<xsl:template match="Settlement[@id='village_V6_1']"/>
	<xsl:template match="Settlement[@id='village_V6_2']"/>
	<xsl:template match="Settlement[@id='village_V6_3']"/>
	<xsl:template match="Settlement[@id='village_V6_4']"/>
	<xsl:template match="Settlement[@id='town_V7']"/>
	<xsl:template match="Settlement[@id='village_V7_1']"/>
	<xsl:template match="Settlement[@id='village_V7_2']"/>
	<xsl:template match="Settlement[@id='town_V8']"/>
	<xsl:template match="Settlement[@id='village_V8_1']"/>
	<xsl:template match="Settlement[@id='village_V8_2']"/>
	<xsl:template match="Settlement[@id='village_V8_3']"/>
	<xsl:template match="Settlement[@id='town_V9']"/>
	<xsl:template match="Settlement[@id='village_V9_1']"/>
	<xsl:template match="Settlement[@id='village_V9_2']"/>
	<!-- Castles -->
	<xsl:template match="Settlement[@id='castle_V1']"/>
	<xsl:template match="Settlement[@id='castle_village_V1_1']"/>
	<xsl:template match="Settlement[@id='castle_V2']"/>
	<xsl:template match="Settlement[@id='castle_village_V2_1']"/>
	<xsl:template match="Settlement[@id='castle_village_V2_2']"/>
	<xsl:template match="Settlement[@id='castle_V3']"/>
	<xsl:template match="Settlement[@id='castle_village_V3_1']"/>
	<xsl:template match="Settlement[@id='castle_village_V3_2']"/>
	<xsl:template match="Settlement[@id='castle_V4']"/>
	<xsl:template match="Settlement[@id='castle_village_V4_1']"/>
	<xsl:template match="Settlement[@id='castle_V5']"/>
	<xsl:template match="Settlement[@id='castle_village_V5_1']"/>
	<xsl:template match="Settlement[@id='castle_village_V5_2']"/>
	<xsl:template match="Settlement[@id='castle_V6']"/>
	<xsl:template match="Settlement[@id='castle_village_V6_1']"/>
	<xsl:template match="Settlement[@id='castle_village_V6_2']"/>
	<xsl:template match="Settlement[@id='castle_V7']"/>
	<xsl:template match="Settlement[@id='castle_village_V7_1']"/>
	<xsl:template match="Settlement[@id='castle_village_V7_2']"/>
	<xsl:template match="Settlement[@id='castle_V8']"/>
	<xsl:template match="Settlement[@id='castle_village_V8_1']"/>
	<xsl:template match="Settlement[@id='castle_village_V8_2']"/>
	
	<!-- Battania -->
	<xsl:template match="Settlement[@id='town_B1']"/>
	<xsl:template match="Settlement[@id='village_B1_1']"/>
	<xsl:template match="Settlement[@id='village_B1_2']"/>
	<xsl:template match="Settlement[@id='village_B1_3']"/>
	<xsl:template match="Settlement[@id='village_B1_4']"/>
	<xsl:template match="Settlement[@id='town_B2']"/>
	<xsl:template match="Settlement[@id='village_B2_1']"/>
	<xsl:template match="Settlement[@id='village_B2_2']"/>
	<xsl:template match="Settlement[@id='village_B2_3']"/>
	<xsl:template match="Settlement[@id='town_B3']"/>
	<xsl:template match="Settlement[@id='village_B3_1']"/>
	<xsl:template match="Settlement[@id='village_B3_2']"/>
	<xsl:template match="Settlement[@id='village_B3_3']"/>
	<xsl:template match="Settlement[@id='town_B4']"/>
	<xsl:template match="Settlement[@id='village_B4_1']"/>
	<xsl:template match="Settlement[@id='village_B4_2']"/>
	<xsl:template match="Settlement[@id='village_B4_3']"/>
	<xsl:template match="Settlement[@id='village_B4_4']"/>
	<xsl:template match="Settlement[@id='town_B5']"/>
	<xsl:template match="Settlement[@id='village_B5_1']"/>
	<xsl:template match="Settlement[@id='village_B5_2']"/>
	<xsl:template match="Settlement[@id='village_B5_3']"/>
	<!-- Castles -->
	<xsl:template match="Settlement[@id='castle_B1']"/>
	<xsl:template match="Settlement[@id='castle_village_B1_1']"/>
	<xsl:template match="Settlement[@id='castle_village_B1_2']"/>
	<xsl:template match="Settlement[@id='castle_B2']"/>
	<xsl:template match="Settlement[@id='castle_village_B2_1']"/>
	<xsl:template match="Settlement[@id='castle_village_B2_2']"/>
	<xsl:template match="Settlement[@id='castle_B3']"/>
	<xsl:template match="Settlement[@id='castle_village_B3_1']"/>
	<xsl:template match="Settlement[@id='castle_village_B3_2']"/>
	<xsl:template match="Settlement[@id='castle_B4']"/>
	<xsl:template match="Settlement[@id='castle_village_B4_1']"/>
	<xsl:template match="Settlement[@id='castle_village_B4_2']"/>
	<xsl:template match="Settlement[@id='castle_B5']"/>
	<xsl:template match="Settlement[@id='castle_village_B5_1']"/>
	<xsl:template match="Settlement[@id='castle_village_B5_2']"/>
	<xsl:template match="Settlement[@id='castle_B6']"/>
	<xsl:template match="Settlement[@id='castle_village_B6_1']"/>
	<xsl:template match="Settlement[@id='castle_village_B6_2']"/>
	<xsl:template match="Settlement[@id='castle_B7']"/>
	<xsl:template match="Settlement[@id='castle_village_B7_1']"/>
	<xsl:template match="Settlement[@id='castle_village_B7_2']"/>
	<xsl:template match="Settlement[@id='castle_B8']"/>
	<xsl:template match="Settlement[@id='castle_village_B8_1']"/>
	<xsl:template match="Settlement[@id='castle_village_B8_2']"/>

	<!-- Khuzait -->
	<xsl:template match="Settlement[@id='town_K1']"/>
	<xsl:template match="Settlement[@id='village_K1_1']"/>
	<xsl:template match="Settlement[@id='village_K1_2']"/>
	<xsl:template match="Settlement[@id='village_K1_4']"/>
	<xsl:template match="Settlement[@id='town_K2']"/>
	<xsl:template match="Settlement[@id='village_K2_1']"/>
	<xsl:template match="Settlement[@id='village_K2_2']"/>
	<xsl:template match="Settlement[@id='town_K3']"/>
	<xsl:template match="Settlement[@id='village_K3_1']"/>
	<xsl:template match="Settlement[@id='village_K3_2']"/>
	<xsl:template match="Settlement[@id='village_K3_3']"/>
	<xsl:template match="Settlement[@id='town_K4']"/>
	<xsl:template match="Settlement[@id='village_K4_2']"/>
	<xsl:template match="Settlement[@id='village_K4_3']"/>
	<xsl:template match="Settlement[@id='village_K4_4']"/>
	<xsl:template match="Settlement[@id='town_K5']"/>
	<xsl:template match="Settlement[@id='village_K5_2']"/>
	<xsl:template match="Settlement[@id='village_K5_3']"/>
	<xsl:template match="Settlement[@id='village_K5_4']"/>
	<xsl:template match="Settlement[@id='town_K6']"/>
	<xsl:template match="Settlement[@id='village_K6_1']"/>
	<xsl:template match="Settlement[@id='village_K6_2']"/>
	<xsl:template match="Settlement[@id='village_K6_3']"/>
	<!-- Castles -->
	<xsl:template match="Settlement[@id='castle_K1']"/>
	<xsl:template match="Settlement[@id='castle_village_K1_1']"/>
	<xsl:template match="Settlement[@id='castle_village_K1_2']"/>
	<xsl:template match="Settlement[@id='castle_K2']"/>
	<xsl:template match="Settlement[@id='castle_village_K2_1']"/>
	<xsl:template match="Settlement[@id='castle_village_K2_2']"/>
	<xsl:template match="Settlement[@id='castle_K3']"/>
	<xsl:template match="Settlement[@id='castle_village_K3_1']"/>
	<xsl:template match="Settlement[@id='castle_village_K3_2']"/>
	<xsl:template match="Settlement[@id='castle_K4']"/>
	<xsl:template match="Settlement[@id='castle_village_K4_1']"/>
	<xsl:template match="Settlement[@id='castle_village_K4_2']"/>
	<xsl:template match="Settlement[@id='castle_K5']"/>
	<xsl:template match="Settlement[@id='castle_village_K5_1']"/>
	<xsl:template match="Settlement[@id='castle_village_K5_2']"/>
	<xsl:template match="Settlement[@id='castle_K6']"/>
	<xsl:template match="Settlement[@id='castle_village_K6_1']"/>
	<xsl:template match="Settlement[@id='castle_village_K6_2']"/>
	<xsl:template match="Settlement[@id='castle_K7']"/>
	<xsl:template match="Settlement[@id='castle_village_K7_1']"/>
	<xsl:template match="Settlement[@id='castle_village_K7_2']"/>
	<xsl:template match="Settlement[@id='castle_K8']"/>
	<xsl:template match="Settlement[@id='castle_village_K8_1']"/>
	<xsl:template match="Settlement[@id='castle_village_K8_2']"/>
	<xsl:template match="Settlement[@id='castle_K9']"/>
	<xsl:template match="Settlement[@id='castle_village_K9_1']"/>
	<xsl:template match="Settlement[@id='castle_village_K9_2']"/>

</xsl:stylesheet>