<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output omit-xml-declaration="yes"/>
	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>
	<!-- Aserai -->
	<!-- Troops -->
	<xsl:template match="NPCCharacter[@id='aserai_recruit']"/>
	<xsl:template match="NPCCharacter[@id='aserai_tribesman']"/>
	<xsl:template match="NPCCharacter[@id='aserai_mameluke_soldier']"/>
	<xsl:template match="NPCCharacter[@id='aserai_skirmisher']"/>
	<xsl:template match="NPCCharacter[@id='aserai_footman']"/>
	<xsl:template match="NPCCharacter[@id='aserai_infantry']"/>
	<xsl:template match="NPCCharacter[@id='aserai_archer']"/>
	<xsl:template match="NPCCharacter[@id='aserai_master_archer']"/>
	<xsl:template match="NPCCharacter[@id='aserai_veteran_infantry']"/>
	<xsl:template match="NPCCharacter[@id='aserai_mameluke_soldier']"/>
	<xsl:template match="NPCCharacter[@id='aserai_mameluke_regular']"/>
	<xsl:template match="NPCCharacter[@id='aserai_mameluke_axeman']"/>
	<xsl:template match="NPCCharacter[@id='aserai_mameluke_cavalry']"/>
	<xsl:template match="NPCCharacter[@id='aserai_mameluke_heavy_cavalry']"/>
	<xsl:template match="NPCCharacter[@id='aserai_mameluke_guard']"/>
	<xsl:template match="NPCCharacter[@id='mamluke_palace_guard']"/>
	<xsl:template match="NPCCharacter[@id='aserai_youth']"/>
	<xsl:template match="NPCCharacter[@id='aserai_tribal_horseman']"/>
	<xsl:template match="NPCCharacter[@id='aserai_faris']"/>
	<xsl:template match="NPCCharacter[@id='aserai_veteran_faris']"/>
	<xsl:template match="NPCCharacter[@id='aserai_vanguard_faris']"/>
	<xsl:template match="NPCCharacter[@id='aserai_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='aserai_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='aserai_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='aserai_militia_veteran_archer']"/>
	<!-- General NPCs -->
	<xsl:template match="NPCCharacter[@id='tournament_master_aserai']"/>
	<xsl:template match="NPCCharacter[@id='villager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_aserai']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_aserai']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='aserai_duel_preset']"/>
	<xsl:template match="NPCCharacter[@id='prison_guard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='guard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_aserai']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townsman_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_aserai']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_aserai']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_aserai']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_aserai']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_aserai']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_aserai']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_aserai']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_aserai']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_aserai']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_aserai']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_aserai']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_aserai']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_aserai']"/>
	<xsl:template match="NPCCharacter[@id='musician_aserai']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_aserai']"/>
	<xsl:template match="NPCCharacter[@id='armorer_aserai']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='barber_aserai']"/>
	<xsl:template match="NPCCharacter[@id='merchant_aserai']"/>
	<xsl:template match="NPCCharacter[@id='beggar_aserai']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_aserai']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_aserai']"/>
	<xsl:template match="NPCCharacter[@id='gear_practice_dummy_aserai']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_1_aserai']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_2_aserai']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_3_aserai']"/>
	<xsl:template match="NPCCharacter[@id='gear_dummy_aserai']"/>
	<!-- Tournaments -->
	<xsl:template match="NPCCharacter[@id='tournament_template_aserai_one_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_aserai_two_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_aserai_two_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_aserai_two_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_aserai_four_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_aserai_four_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_aserai_four_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_aserai_four_participant_set_v4']"/>
	
	<!-- Battania -->
	<!-- Troops -->
	<xsl:template match="NPCCharacter[@id='battanian_volunteer']"/>
	<xsl:template match="NPCCharacter[@id='battanian_clanwarrior']"/>
	<xsl:template match="NPCCharacter[@id='battanian_woodrunner']"/>
	<xsl:template match="NPCCharacter[@id='battanian_trained_warrior']"/>
	<xsl:template match="NPCCharacter[@id='battanian_picked_warrior']"/>
	<xsl:template match="NPCCharacter[@id='battanian_scout']"/>
	<xsl:template match="NPCCharacter[@id='battanian_oathsworn']"/>
	<xsl:template match="NPCCharacter[@id='battanian_horseman']"/>
	<xsl:template match="NPCCharacter[@id='battanian_mounted_skirmisher']"/>
	<xsl:template match="NPCCharacter[@id='battanian_raider']"/>
	<xsl:template match="NPCCharacter[@id='battanian_skirmisher']"/>
	<xsl:template match="NPCCharacter[@id='battanian_falxman']"/>
	<xsl:template match="NPCCharacter[@id='battanian_veteran_skirmisher']"/>
	<xsl:template match="NPCCharacter[@id='battanian_wildling']"/>
	<xsl:template match="NPCCharacter[@id='battanian_veteran_falxman']"/>
	<xsl:template match="NPCCharacter[@id='battanian_highborn_youth']"/>
	<xsl:template match="NPCCharacter[@id='battanian_highborn_warrior']"/>
	<xsl:template match="NPCCharacter[@id='battanian_hero']"/>
	<xsl:template match="NPCCharacter[@id='battanian_fian']"/>
	<xsl:template match="NPCCharacter[@id='battanian_fian_champion']"/>
	<xsl:template match="NPCCharacter[@id='battanian_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='battanian_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='battanian_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='battanian_militia_veteran_archer']"/>
	<!-- General NPCs -->
	<xsl:template match="NPCCharacter[@id='tournament_master_battania']"/>
	<xsl:template match="NPCCharacter[@id='villager_battania']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_battania']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_battania']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_battania']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_battania']"/>
	<xsl:template match="NPCCharacter[@id='battania_duel_preset']"/>
	<xsl:template match="NPCCharacter[@id='prison_guard_battania']"/>
	<xsl:template match="NPCCharacter[@id='guard_battania']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_battania']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_battania']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_battania']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_battania']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_battania']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_battania']"/>
	<xsl:template match="NPCCharacter[@id='townsman_battania']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_battania']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_battania']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_battania']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_battania']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_battania']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_battania']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_battania']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_battania']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_battania']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_battania']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_battania']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_battania']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_battania']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_battania']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_battania']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_battania']"/>
	<xsl:template match="NPCCharacter[@id='musician_battania']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_battania']"/>
	<xsl:template match="NPCCharacter[@id='armorer_battania']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_battania']"/>
	<xsl:template match="NPCCharacter[@id='barber_battania']"/>
	<xsl:template match="NPCCharacter[@id='merchant_battania']"/>
	<xsl:template match="NPCCharacter[@id='beggar_battania']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_battania']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_battania']"/>
	<xsl:template match="NPCCharacter[@id='gear_practice_dummy_battania']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_1_battania']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_2_battania']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_3_battania']"/>
	<xsl:template match="NPCCharacter[@id='gear_dummy_battania']"/>
	<!-- Tournaments -->
	<xsl:template match="NPCCharacter[@id='tournament_template_battania_one_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_battania_two_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_battania_two_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_battania_two_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_battania_four_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_battania_four_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_battania_four_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_battania_four_participant_set_v4']"/>
	
	<!-- Empire -->
	<!-- Troops -->
	<xsl:template match="NPCCharacter[@id='imperial_recruit']"/>
	<xsl:template match="NPCCharacter[@id='imperial_infantryman']"/>
	<xsl:template match="NPCCharacter[@id='imperial_trained_infantryman']"/>
	<xsl:template match="NPCCharacter[@id='imperial_veteran_infantryman']"/>
	<xsl:template match="NPCCharacter[@id='imperial_legionary']"/>
	<xsl:template match="NPCCharacter[@id='imperial_menavliaton']"/>
	<xsl:template match="NPCCharacter[@id='imperial_elite_menavliaton']"/>
	<xsl:template match="NPCCharacter[@id='imperial_archer']"/>
	<xsl:template match="NPCCharacter[@id='imperial_trained_archer']"/>
	<xsl:template match="NPCCharacter[@id='imperial_veteran_archer']"/>
	<xsl:template match="NPCCharacter[@id='imperial_palatine_guard']"/>
	<xsl:template match="NPCCharacter[@id='imperial_crossbowman']"/>
	<xsl:template match="NPCCharacter[@id='imperial_sergeant_crossbowman']"/>
	<xsl:template match="NPCCharacter[@id='bucellarii']"/>
	<xsl:template match="NPCCharacter[@id='imperial_vigla_recruit']"/>
	<xsl:template match="NPCCharacter[@id='imperial_equite']"/>
	<xsl:template match="NPCCharacter[@id='imperial_heavy_horseman']"/>
	<xsl:template match="NPCCharacter[@id='imperial_cataphract']"/>
	<xsl:template match="NPCCharacter[@id='imperial_elite_cataphract']"/>
	<xsl:template match="NPCCharacter[@id='imperial_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='imperial_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='imperial_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='imperial_militia_veteran_archer']"/>
	<!-- General NPCs -->
	<xsl:template match="NPCCharacter[@id='tournament_master_empire']"/>
	<xsl:template match="NPCCharacter[@id='villager_empire']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_empire']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_empire']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_empire']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_empire']"/>
	<xsl:template match="NPCCharacter[@id='empire_duel_preset']"/>
	<xsl:template match="NPCCharacter[@id='prison_guard_empire']"/>
	<xsl:template match="NPCCharacter[@id='guard_empire']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_empire']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_empire']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_empire']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_empire']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_empire']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_empire']"/>
	<xsl:template match="NPCCharacter[@id='townsman_empire']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_empire']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_empire']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_empire']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_empire']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_empire']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_empire']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_empire']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_empire']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_empire']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_empire']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_empire']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_empire']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_empire']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_empire']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_empire']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_empire']"/>
	<xsl:template match="NPCCharacter[@id='musician_empire']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_empire']"/>
	<xsl:template match="NPCCharacter[@id='armorer_empire']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_empire']"/>
	<xsl:template match="NPCCharacter[@id='barber_empire']"/>
	<xsl:template match="NPCCharacter[@id='merchant_empire']"/>
	<xsl:template match="NPCCharacter[@id='beggar_empire']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_empire']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_empire']"/>
	<xsl:template match="NPCCharacter[@id='gear_practice_dummy_empire']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_1_empire']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_2_empire']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_3_empire']"/>
	<xsl:template match="NPCCharacter[@id='gear_dummy_empire']"/>
	<!-- Tournaments -->
	<xsl:template match="NPCCharacter[@id='tournament_template_empire_one_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_empire_two_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_empire_two_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_empire_two_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_empire_four_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_empire_four_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_empire_four_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_empire_four_participant_set_v4']"/>
	
	<!-- Khuzait -->
	<!-- Troops -->
	<xsl:template match="NPCCharacter[@id='khuzait_nomad']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_footman']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_tribal_warrior']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_noble_son']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_hunter']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_spearman']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_raider']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_horseman']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_qanqli']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_archer']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_spear_infantry']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_horse_archer']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_lancer']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_torguud']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_marksman']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_darkhan']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_heavy_horse_archer']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_heavy_lancer']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_kheshig']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_khans_guard']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_militia_veteran_archer']"/>
	<!-- General NPCs -->
	<xsl:template match="NPCCharacter[@id='tournament_master_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='villager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='khuzait_duel_preset']"/>
	<xsl:template match="NPCCharacter[@id='prison_guard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='guard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townsman_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='musician_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='armorer_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='barber_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='merchant_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='beggar_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='gear_practice_dummy_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_1_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_2_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_3_khuzait']"/>
	<xsl:template match="NPCCharacter[@id='gear_dummy_khuzait']"/>
	<!-- Tournaments -->
	<xsl:template match="NPCCharacter[@id='tournament_template_khuzait_one_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_khuzait_two_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_khuzait_two_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_khuzait_two_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_khuzait_four_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_khuzait_four_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_khuzait_four_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_khuzait_four_participant_set_v4']"/>
	
	<!-- Sturgia -->
	<!-- Troops -->
	<xsl:template match="NPCCharacter[@id='sturgian_recruit']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_warrior']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_soldier']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_shock_troop']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_veteran_warrior']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_warrior_son']"/>
	<xsl:template match="NPCCharacter[@id='varyag']"/>
	<xsl:template match="NPCCharacter[@id='varyag_veteran']"/>
	<xsl:template match="NPCCharacter[@id='druzhinnik']"/>
	<xsl:template match="NPCCharacter[@id='druzhinnik_champion']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_woodsman']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_hunter']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_archer']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_veteran_bowman']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_brigand']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_hardened_brigand']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_horse_raider']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_berzerker']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_spearman']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_ulfhednar']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='sturgian_militia_veteran_archer']"/>
	<!-- General NPCs -->
	<xsl:template match="NPCCharacter[@id='tournament_master_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='villager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='sturgia_duel_preset']"/>
	<xsl:template match="NPCCharacter[@id='prison_guard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='guard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='musician_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='armorer_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='barber_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='merchant_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='beggar_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='gear_practice_dummy_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_1_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_2_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_3_sturgia']"/>
	<xsl:template match="NPCCharacter[@id='gear_dummy_sturgia']"/>
	<!-- Tournaments -->
	<xsl:template match="NPCCharacter[@id='tournament_template_sturgia_one_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_sturgia_two_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_sturgia_two_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_sturgia_two_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_sturgia_four_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_sturgia_four_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_sturgia_four_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_sturgia_four_participant_set_v4']"/>
	
	<!-- Vlandia -->
	<!-- Troops -->
	<xsl:template match="NPCCharacter[@id='vlandian_recruit']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_footman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_spearman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_billman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_swordsman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_voulgier']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_pikeman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_infantry']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_sergeant']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_levy_crossbowman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_crossbowman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_hardened_crossbowman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_sharpshooter']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_squire']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_light_cavalry']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_cavalry']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_vanguard']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_gallant']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_knight']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_champion']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_banner_knight']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_militia_spearman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_militia_archer']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_militia_veteran_spearman']"/>
	<xsl:template match="NPCCharacter[@id='vlandian_militia_veteran_archer']"/>
	<!-- General NPCs -->
	<xsl:template match="NPCCharacter[@id='tournament_master_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='villager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='caravan_master_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='armed_trader_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='caravan_guard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='veteran_caravan_guard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='vlandia_duel_preset']"/>
	<xsl:template match="NPCCharacter[@id='prison_guard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='guard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='blacksmith_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='weaponsmith_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_infant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_child_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townswoman_teenager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_infant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_child_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='villager_child_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='villager_teenager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_child_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='village_woman_teenager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='townsman_teenager_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='ransom_broker_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='gangleader_bodyguard_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='merchant_notary_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='artisan_notary_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='preacher_notary_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='rural_notable_notary_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='shop_worker_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='tavernkeeper_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='taverngamehost_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='musician_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='tavern_wench_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='armorer_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='horseMerchant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='barber_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='merchant_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='beggar_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='female_beggar_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='female_dancer_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='gear_practice_dummy_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_1_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_2_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='weapon_practice_stage_3_vlandia']"/>
	<xsl:template match="NPCCharacter[@id='gear_dummy_vlandia']"/>
	<!-- Tournaments -->
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_one_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_two_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_two_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_two_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_four_participant_set_v1']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_four_participant_set_v2']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_four_participant_set_v3']"/>
	<xsl:template match="NPCCharacter[@id='tournament_template_vlandia_four_participant_set_v4']"/>
	
	<!-- Mercenary	
	<xsl:template match="NPCCharacter[@id='mercenary_1']"/>
	-->

</xsl:stylesheet>
